#!/usr/bin/env python3
"""Project the private knowledge-quality Issue Ledger into a neutral public aggregate.

Why this exists
----------------
The private Issue Ledger (`.private/knowledge-quality/issues.jsonl`) carries the detail a
reviewer needs: path, owner, remediation direction, dependencies, decision provenance. None of
that belongs in a public repository. What a public reader can use is a count: how many issues of
which category and severity exist, and what lifecycle stage they are in.

Design's Public Aggregate is defined as an allowlist, not a denylist: the generator does not
strip disallowed fields from a private record, it builds a new object containing only
`category`, `severity`, `phase`, `status`, `aggregate_count`, `generated_from_revision`, and
`generated_at`. A denylist silently admits a new private field the day someone adds one to the
ledger schema; an allowlist cannot.

`phase` and `status` are projection-only vocabulary, not ledger fields. The ledger's `state`
(discovered .. accepted-baseline) is already private life-cycle detail; `status` reuses it
directly, and `phase` buckets it into four coarse public-facing stages. Neither is stored on the
ledger record itself, so adding this generator required no change to `issue-ledger.schema.json`.

Generated artifact
------------------
Rendered as a single bilingual file, `docs/ja/reference/knowledge-quality-status.md`, following
the same convention as `docs/ja/reference/cross-repo-index.md`: Japanese is authoritative and English
follows in the same file with the same section structure, so there is no `docs/en/reference/`
counterpart to keep in sync and no `docs/i18n-manifest.txt` entry to add.

The file is generated. Do not hand-edit it. Modes, matching `sync_lang_switcher.py`:

    python3 tools/project_public_aggregate.py            # check: fail if the file is stale
    python3 tools/project_public_aggregate.py --write    # regenerate it from the ledger
    python3 tools/project_public_aggregate.py --allow-missing-ledger   # CI: INCONCLUSIVE if no ledger

The private ledger lives under `.private/`, which is gitignored and therefore absent in CI. Without
the ledger the count cannot be checked against it, so demanding the tracked file equal an empty
aggregate would fail forever. `--allow-missing-ledger` reports INCONCLUSIVE in that case — after
verifying the tracked file exists and is the well-formed generated document — following the same
three-state discipline as the cross-repository external check. The flag is deliberately not the
default: where the ledger is present (local, pre-commit) its absence is an error, so deleting it by
accident is caught rather than silently turning the check off. `--write` never honours the flag,
because regenerating from an absent ledger would overwrite the tracked file with an empty aggregate.

The check ignores `generated_at`, which changes on every run by design, so a stale-content check
cannot be defeated by regenerating at a different second, and cannot falsely fail on a rerun at
the same content. `generated_from_revision` is the SHA-256 of the ledger file's bytes, computed at
run time — never hand-maintained, so it changes exactly when the content it describes does.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from collections.abc import Iterable, Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from issue_ledger import validation_errors

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / ".private" / "knowledge-quality" / "issues.jsonl"
OUTPUT = ROOT / "docs" / "ja" / "reference" / "knowledge-quality-status.md"

# The only fields a projected row may carry. Adding a field here is a design decision, not a
# generator convenience, because everything listed here is public.
ALLOWED_ROW_FIELDS = (
    "category",
    "severity",
    "phase",
    "status",
    "aggregate_count",
)

# state -> phase. A coarse public bucket, defined once here and nowhere else; it is not stored on
# the ledger record itself, so a ledger schema change cannot silently drift it.
_PHASE_BY_STATE = {
    "discovered": "discovered",
    "triaged": "discovered",
    "blocked": "in-progress",
    "planned": "in-progress",
    "fixing": "in-progress",
    "verifying": "verifying",
    "resolved": "resolved",
    "accepted-baseline": "resolved",
}

HEADER = """\
<!-- generated by tools/project_public_aggregate.py from the private Issue Ledger. -->
<!-- Do not hand-edit. Regenerate with: python3 tools/project_public_aggregate.py --write -->

"""


def phase_for_state(state: str) -> str:
    """Coarse public phase bucket for one ledger state. Raises on an unknown state on purpose:
    a state this function does not recognize must not silently fall into an existing bucket."""
    try:
        return _PHASE_BY_STATE[state]
    except KeyError:
        raise ValueError(
            f"no public phase bucket defined for ledger state {state!r}"
        ) from None


def read_ledger_records(path: Path) -> list[dict[str, Any]]:
    """Parse ledger records, skipping and warning on any line that fails schema validation.

    A malformed or incomplete record must not silently vanish from the count, and it must not
    silently appear either — it is reported to stderr and excluded, the same "reject rather than
    guess" rule the rest of the validators in this repository follow.
    """
    if not path.exists():
        return []
    records: list[dict[str, Any]] = []
    for lineno, raw in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            print(f"{path}:{lineno}: skipped, invalid JSON: {exc}", file=sys.stderr)
            continue
        errors = validation_errors(record)
        if errors:
            print(
                f"{path}:{lineno}: skipped, invalid ledger record: {'; '.join(errors)}",
                file=sys.stderr,
            )
            continue
        records.append(record)
    return records


def aggregate_rows(records: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
    """Group valid records by (category, severity, phase, status) and count each group."""
    counts: Counter[tuple[str, str, str, str]] = Counter()
    for record in records:
        state = record["state"]
        key = (record["category"], record["severity"], phase_for_state(state), state)
        counts[key] += 1
    rows = [
        {
            "category": category,
            "severity": severity,
            "phase": phase,
            "status": status,
            "aggregate_count": count,
        }
        for (category, severity, phase, status), count in counts.items()
    ]
    rows.sort(
        key=lambda row: (row["category"], row["severity"], row["phase"], row["status"])
    )
    for row in rows:
        assert set(row) == set(ALLOWED_ROW_FIELDS)
    return rows


def ledger_digest(path: Path) -> str:
    if not path.exists():
        return "sha256:" + "0" * 64
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _table(
    rows: list[dict[str, Any]], headers: tuple[str, str, str, str, str]
) -> list[str]:
    lines = [f"| {' | '.join(headers)} |", "|" + "---|" * len(headers)]
    for row in rows:
        lines.append(
            f"| {row['category']} | {row['severity']} | {row['phase']} | {row['status']} | "
            f"{row['aggregate_count']} |"
        )
    return lines


def render(
    rows: list[dict[str, Any]], *, generated_from_revision: str, generated_at: str
) -> str:
    """Render the bilingual generated document. `generated_at` is the only field that changes on
    every run without changing what the document says; the drift check excludes it accordingly."""
    total = sum(row["aggregate_count"] for row in rows)
    lines = [
        HEADER.rstrip("\n"),
        "",
        "# 知識品質状況 / Knowledge Quality Status",
        "",
        "## 概要",
        "",
        (
            f"非公開の Issue Ledger から生成した集計です。件数と分類だけを示し、"
            f"個別の所見、対象パス、担当、レビュー履歴は含みません。現在の件数: {total}。"
        ),
        "",
        "## Overview",
        "",
        (
            f"Generated from the private Issue Ledger. Shows only counts and classification, "
            f"never individual findings, paths, owners, or review history. Current count: {total}."
        ),
        "",
        "## 分類別集計",
        "",
        *_table(rows, ("category", "severity", "phase", "status", "aggregate_count")),
        "",
        "## Aggregate by Classification",
        "",
        *_table(rows, ("category", "severity", "phase", "status", "aggregate_count")),
        "",
        "## Provenance",
        "",
        f"- `generated_from_revision`: `{generated_from_revision}`",
        f"- `generated_at`: `{generated_at}`",
    ]
    return "\n".join(lines) + "\n"


def _without_generated_at(text: str) -> str:
    """Strip the one line whose value is expected to change on every run."""
    return "\n".join(
        line for line in text.splitlines() if not line.startswith("- `generated_at`:")
    )


def _check_generated_file_health() -> int:
    """Validate the tracked artifact without the ledger: it must exist and parse as the generated
    document (header present, the two mandatory sections present). This is what an environment
    without the private ledger — CI — can still verify: that the committed file is not missing and
    not corrupt. It cannot verify the counts match the ledger, because the ledger is absent."""
    if not OUTPUT.exists():
        print(
            f"{OUTPUT.relative_to(ROOT)} is missing. Run "
            "`python3 tools/project_public_aggregate.py --write` to create it",
            file=sys.stderr,
        )
        return 1
    current = OUTPUT.read_text(encoding="utf-8")
    required_markers = (
        "generated by tools/project_public_aggregate.py",
        "# 知識品質状況 / Knowledge Quality Status",
        "## 概要",
        "## Overview",
        "## Provenance",
    )
    missing = [marker for marker in required_markers if marker not in current]
    if missing:
        print(
            f"{OUTPUT.relative_to(ROOT)} exists but is not the generated document "
            f"(missing: {'; '.join(missing)}). Regenerate with "
            "`python3 tools/project_public_aggregate.py --write`",
            file=sys.stderr,
        )
        return 1
    print(
        "knowledge-quality-status: INCONCLUSIVE — the private ledger is absent, so the counts "
        "cannot be checked against it. The tracked file exists and is well-formed. "
        "(Run without --allow-missing-ledger where the ledger is present to check drift.)"
    )
    return 0


def check(*, write: bool, allow_missing_ledger: bool = False) -> int:
    # A missing ledger is handled up front, and the two branches are the whole point of the flag.
    # On --write it is neither: writing regenerates the tracked file from whatever the ledger holds
    # (including nothing), so an absent ledger there is not special.
    if not write and not LEDGER.exists():
        if allow_missing_ledger:
            # CI, which has no .private/. Do not treat an empty ledger as "zero rows" and compare
            # against the tracked file — an empty ledger renders an empty aggregate, so a non-empty
            # committed file would fail forever and an empty one would pass without checking
            # anything. Verify the file's health instead and report INCONCLUSIVE.
            return _check_generated_file_health()
        # The local / pre-commit default. Without the flag, an absent ledger is an error rather
        # than a silent pass. This is the exact hole the flag makes explicit: if this returned 0
        # (empty ledger renders empty aggregate, which matches an empty tracked file), deleting the
        # ledger locally would turn the drift check off with no signal.
        print(
            f"the private ledger {LEDGER.relative_to(ROOT)} is absent. This check compares the "
            "public aggregate against it, so with no ledger there is nothing to check. Pass "
            "--allow-missing-ledger only where the ledger is expected to be absent (CI); its "
            "absence locally is an error, not a free pass",
            file=sys.stderr,
        )
        return 1

    records = read_ledger_records(LEDGER)
    rows = aggregate_rows(records)
    generated_at = datetime.now(UTC).isoformat().replace("+00:00", "Z")
    fresh = render(
        rows, generated_from_revision=ledger_digest(LEDGER), generated_at=generated_at
    )

    if write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(fresh, encoding="utf-8")
        print(
            f"knowledge-quality-status: wrote {len(rows)} row(s) to {OUTPUT.relative_to(ROOT)}"
        )
        return 0

    if not OUTPUT.exists():
        print(
            f"{OUTPUT.relative_to(ROOT)} is missing. Run "
            "`python3 tools/project_public_aggregate.py --write` to create it",
            file=sys.stderr,
        )
        return 1
    current = OUTPUT.read_text(encoding="utf-8")
    if _without_generated_at(current) != _without_generated_at(fresh):
        print(
            f"{OUTPUT.relative_to(ROOT)} is stale relative to the ledger. Regenerate with "
            "`python3 tools/project_public_aggregate.py --write`",
            file=sys.stderr,
        )
        return 1
    print(f"knowledge-quality-status: {len(rows)} row(s), up to date with the ledger")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the public aggregate from the ledger",
    )
    parser.add_argument(
        "--allow-missing-ledger",
        action="store_true",
        help=(
            "when the private ledger is absent, report INCONCLUSIVE instead of failing. "
            "Use in CI where .private/ is gitignored and never present. "
            "Without this flag (the local/pre-commit default) a missing ledger is an error, "
            "so accidentally deleting it is caught rather than silently ignored."
        ),
    )
    args = parser.parse_args()
    return check(write=args.write, allow_missing_ledger=args.allow_missing_ledger)


if __name__ == "__main__":
    sys.exit(main())
